Output assets/demo.gif

Set Theme "Catppuccin Mocha"
Set Shell fish
Set FontSize 14
Set FontFamily "JetBrainsMono Nerd Font"

Set Width 1600
Set Height 800
Set Framerate 30
Set Padding 12

Hide
Type gh ci
Enter
Sleep 3s
Show

Sleep 1s
Set TypingSpeed 400ms

Type "j"
Type "k"
Sleep 1s
Enter

Sleep 1s

Type "j"
Type "j"
Type "j"
Type "j"
Type "j"
Type "j"
Sleep 1.5s
Enter
Type "j"
Type "j"

Sleep 3s